contentColumnType: string
fieldGroup: f445487e-f6a2-471c-a08b-3096f57da2d0
handle: tags
instructions: null
name: Tags
searchable: true
settings:
  localizeRelations: false
  source: 'taggroup:237da2ff-504f-4e2c-bf6c-152bf831c8f1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Tags
