contentColumnType: string
fieldGroup: f445487e-f6a2-471c-a08b-3096f57da2d0
handle: teaserCopy
instructions: ''
name: 'Teaser Copy'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: '1'
  columnType: text
  configFile: Simple.json
  purifyHtml: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
